### ISSUE TITLE
No transformtion is being applied

### ISSUE THREAD

**Issue by josias-r** [getsentry/sentry-migr8#45]
### Environment

```
  System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 53.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
```

### Steps to Reproduce

Reproduction repo: https://github.com/josias-r/sentry-upgrade

- Running `npx @sentry/migr8@latest --debug` does nothing besides upgrading the npm package.
- Conventional NextJS TypeScript project
- running with debug shows all files being SKIPPED
- I tried with several fileInclude/Exclude patterns and other arguments, nothing worked.

### Expected Result

I would expect it to apply codemods, such as moving to the transformations TS file, etc.

### Actual Result

The NPM package upgrade is the ONLY change that is being applied (I could have done that myself 😜)

**Comment by josias-r** [comment]
https://github.com/getsentry/sentry-migr8/assets/11424820/f4c28322-5f7f-4540-bab2-12b6bf0aa35d

**Comment by Lms24** [comment]
Hey, thanks for letting us know and for the reproduction! I'll look into this today! 

For now, to unblock you, I suggest to manually follow our [migration guide for NextJS](https://docs.sentry.io/platforms/javascript/guides/nextjs/migration/v7-to-v8/#upgrading-to-8x). If you don't have a ton of custom Sentry setup, it shouldn't be too much work 🤞 

Regardless, sorry for the inconvenience!

**Comment by josias-r** [comment]
Thank you! I will look into manual migration 😁

**Comment by Lms24** [comment]
Hey @josias-r I checked out your repro app and if I just run `npx @sentry/migr8@latest` I can confirm that no code changes are applied. Only the package is updated. That's because at least your repro app is already up to date otherwise 🚀 

With one exception: We should write a migration for NextJS specifically to move the SDK initialization to `instrumentation.ts` file, as documented in the migration guide. I'm gonna add this to our list in #49 and we'll take a look. Sorry that this experience isn't optimal for nextJS.

**Comment by josias-r** [comment]
@Lms24 Oh okay I see. The instrumentation TS file was literally the only change I was looking for as confirmation the migration worked, and since it didn't happen I simply assumed all the transformation are not working.

Thank you for the explanation!
